# файл Docker Compose, который используется для управления контейнерами Docker. 
# В данном случае он описывает контейнер с именем "snils_mock", который основан на образе "snils_mock". 
# Контейнер имеет порт 8088, который прослушивает входящие соединения на хосте и перенаправляет их на порт 8088 внутри контейнера. 
# Также указаны ограничения ресурсов для контейнера: половина ядра процессора и 512 МБ оперативной памяти.

version: '3.8'
services:
  snils_mock:
    build:
      context: .
      dockerfile: Dockerfile
    image: snils_mock
    container_name: snils_mock
    ports:
      - "8088:8088"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M